CREATE TABLE [dbo].[Users] (
    [id]      INT            IDENTITY (1, 1) NOT NULL,
    [name]    NVARCHAR (255) NOT NULL,
    [email]   NVARCHAR (255) NOT NULL,
    [roles]   NVARCHAR (255) NULL,
    [testMsg] NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

